# Generated by Django 3.0.7 on 2020-06-30 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tambola', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Player',
        ),
    ]
